### PR TITLE
Move login parameters from query to post body

### PR DESCRIPTION
**Pull request by ransombriggs**

### CODE REVIEW

**Comment by geemus** [comment]
Appears to not work in 1.8 due to the encoding method not being defined (and 1.9 is failing, but I'm really not sure what's going on there). Otherwise the change seems good, but probably should try to fix those if it isn't too crazy/hard. I guess we should also figure out if/when to drop 1.8 support.

**Comment by ransombriggs** [comment]
@geemus I fixed the 1.8 error by using URI.encode, but I still get a failure in 1.9.3 with `NoMethodError: undefined method `spec' for nil:NilClass` coming from bundler, which seems really odd, any ideas?

**Comment by geemus** [comment]
Seems good now. @ransombriggs I'll let you pull the trigger on the release? That way we can be sure everything is setup properly so you can in case I'm not available next time.
